import type { Metadata } from "next";
import {Rubik, Advent_Pro} from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  subsets:['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-rubik',
});
const advent = Advent_Pro({
  subsets:['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-advent',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${advent.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
